# Este es un ejemplo de pipeline básico
trigger:
  branches:
    include:
      - main

pool:
  name: 'Default' 

steps:
  - script: echo "Agente self-hosted funcionando correctamente"
    displayName: "Verificar agente self-hosted"
  
  # Otros pasos de construcción, prueba o despliegue
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub'
      repository: 'armando24/prueba'
      command: 'pull'