# Este es un ejemplo de pipeline básico
trigger:
  branches:
    include:
      - main

pool:
  name: 'Default' 

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python --version
      echo "Hello World!"
    displayName: 'Run Python script'

